### ISSUE TITLE
Can't download github.sql from https://cdn.gorse.io/example/github.sql

### ISSUE THREAD

**Issue by Febriansz** [gorse-io/gitrec#103]
<img width="1680" alt="Screenshot 2024-05-20 at 09 35 03" src="https://github.com/gorse-io/gitrec/assets/14304241/753e7ade-5906-4167-a56a-581fc3b4ea44">

Does anyone have github.sql file? the link seems dead and I've been retry it every single day but I think it won't be fixed in a while

**Comment by zhenghaoz** [comment]
I'm sorry for not getting back to you sooner. I have recovered the dataset: https://cdn.gorse.io/example/github.sql
