### ISSUE TITLE
[功能请求] 可否直接提供油猴脚本-已迁移完毕

### ISSUE THREAD

**Issue by lisonge** [gorse-io/gitrec#64]
迁移之后的脚本 <https://github.com/lisonge/userscripts/tree/main/packages/gitrec>

迁移之后基于 [vite](https://cn.vitejs.dev/guide/) + [vite-plugin-monkey](https://github.com/lisonge/vite-plugin-monkey/blob/main/README_zh.md) + ts 编写

如果接受，能否发起 pull requests ？或者直接复制进去也行

**Comment by zhenghaoz** [comment]
太棒了，欢迎PR😁可以创建一个userscript目录把源码放进去
