### ISSUE TITLE
live demo on gorse.io seems dead

### ISSUE THREAD

**Issue by orenmizr** [gorse-io/gitrec#87]
shows white screen. no content.

**Comment by zhenghaoz** [comment]
The disk is full. I have fixed it now.

**Comment by TSaltedfishKing** [comment]
ERR_CONNECTION_CLOSED

I can't access the site for a few days.

**Comment by thejawker** [comment]
Yeah it's still dead. Thanks for the project, hoping to use it soon. Appreciate the thoroughness of gorse!

**Comment by veekthoven** [comment]
I hope gorse isn't dead. It's very useful to me 😭

**Comment by genevera** [comment]
SSL cert invalid:

![Screenshot 2024-10-24 at 14 41 45](https://github.com/user-attachments/assets/5f62c405-7ebc-4023-ab16-26e5bdf745e7)

**Comment by zhenghaoz** [comment]
Thank you for your feedback. The demo has been recovered now: [![Website](https://img.shields.io/website?url=https%3A%2F%2Fgitrec.gorse.io)](https://gitrec.gorse.io)
